name: ci

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Test
        run: make test
      - name: Coverage
        run: make cover-check
      - name: Build
        run: make build
